### ISSUE TITLE
h5 error writing results of 400/500 file runs

### ISSUE THREAD

**Issue by martenson** [RECETOX/recetox-aplcms-archive#10]
For 400/500 input files runs we got different errors than for https://github.com/RECETOX/recetox-aplcms/issues/1

```
Error in x$create_dataset(name, value) : HDF5-API Errors:
    error #000: ../../../src/H5D.c in H5Dcreate2(): line 145: unable to create dataset
        class: HDF5
        major: Dataset
        minor: Unable to initialize object

    error #001: ../../../src/H5Dint.c in H5D__create_named(): line 326: unable to create and link to dataset
        class: HDF5
        major: Dataset
        minor: Unable to initialize object

    error #002: ../../../src/H5L.c in H5L_link_object(): line 1572: unable to create new link to object
        class: HDF5
        major: Links
        minor: Unable to initialize object

    error #003: ../../../src/H5L.c in H5L__create_real(): line 1813: can't insert link
        class: HDF5
        major: Links
        minor: Unable to insert object

    error #004: ../../../src/H5Gtraverse.c in H5G_traverse(): line 851: internal path traversal failed
        class: HDF5
        major: Symbol table
        minor: Object not found

    error #005: ../../../src/H5Gtraverse.c in H5G__traverse_re
Calls: <Anonymous> -> [[<- -> [[<-.H5File -> <Anonymous> -> .Call
Execution halted
```

**Comment by xtracko** [comment]
After a little bit of googling, I've stumbled upon [HDF5 limits](https://portal.hdfgroup.org/pages/viewpage.action?pageId=48808714). It mentions that there is a 64 KB limit on object headers stored inside the file.

> There is a limit (in HDF5-1.8) of the object header, which is 64 KB. The datatype for a dataset is stored in the object header, so there is therefore a limit on the size of the datatype that you can have. (See HDFFV-1089) 

So I've pursued it because I had a feeling that we might exceed the limit. The contained `peaks` table has a variable number of columns dependant upon the number of input mzml files.

```python
>>> file = h5py.h5f.open(b'Galaxy3841-[apLCMS_-_100].h5', flags = h5py.h5f.ACC_RDONLY)
>>> info = h5py.h5o.get_info(file, b'peaks')
>>> info.hdr.space.total
20488
>>> file = h5py.h5f.open(b'Galaxy3842-[apLCMS_-300].h5', flags = h5py.h5f.ACC_RDONLY)
>>> info = h5py.h5o.get_info(file, b'peaks')
>>> info.hdr.space.total
60536
```

The header size for 100 files is 20488 bytes and for 300 files is 60536 bytes from the code snippet above. This grows near the 64 KB limit, and thus, the 400 file run fails.

To fix this, we might change the layout of the `peaks` table, or we might "solve" this by transitioning to parquet.

**Comment by martenson** [comment]
A move to parquet is the more plausible option I think. Plus we know what problems with dimensions to look out for.

**Comment by martenson** [comment]
This is seemingly resolved in the latest version that uses parquet and biocontainers.
