### ISSUE TITLE
Missing rgl dependencies

### ISSUE THREAD

**Issue by xtracko** [RECETOX/recetox-aplcms-archive#17]
The library `rgl` unsuccessfully tries to load OpenGL. The following error was detected when running apLCMS on UMSA. It is strange that we didn't catch this during automated testing.

`Error in dyn.load(dynlib <- getDynlib(dir)) : unable to load shared object '/mnt/volume/shared/ces-nya/nfs4/home/umsa/dependencies/_conda/envs/mulled-v1-005e0b0bc1859959b3873283e3ccf66d66f94e5c9dddcaf0bf9295b5bac7e39d/lib/R/library/rgl/libs/rgl.so': libGL.so.1: cannot open shared object file: No such file or directory`

**Comment by martenson** [comment]
I think I have solution for this, testing now.

**Comment by martenson** [comment]
I think this is now resolved. There were multiple problems here, mostly fixed by these PRs:

https://github.com/RECETOX/galaxytools/pull/134
https://github.com/RECETOX/galaxytools/pull/134

In addition OpenGL is not commonly installed on HPC, so our rgl lib ran fine on desktops but failed on UMSA hpc VMs. As a solution we've built a biocontainer for it (https://quay.io/repository/biocontainers/mulled-v2-dceaa6ce3d797c3153f327c7fc15983c4e882d4d?tab=tags) however that unearthed another problem with mulled hashes, that were not matching because we were using `R` dependency instead of `r-base`.

All in all now it seems to work and I am running further tests.
