### ISSUE TITLE
Release Bioconda package

### ISSUE THREAD

**Issue by xtracko** [RECETOX/recetox-aplcms-archive#3]
Current dependency status on conda-forge channel:
- [x]  r-doparallel 
- [x] r-e1071
- [x]  r-foreach 
- [x]  r-gbm 
- [x] r-hdf5r
- [x] r-iterators
- [x] r-mass
- [x]  r-randomforest 
- [x]  r-rcpp 
- [x]  r-rgl 
- [x] r-rocr
- [x] r-rocs
- [x] r-snow
- [x] bioconductor-mzr

We need to package the `ROCS` dependency by ourselves. All the other dependencies are available on `conda-forge` at their latest versions (as of CRAN) (checked on 10th Nov 2020).

Blocking issues:
- [ ] PR to upstream RECETOX/apLCMS#8
- [x] decide proper packaging methods RECETOX/galaxytools#30

**Comment by martenson** [comment]
@maximskorik please update the draft bioconda PR to reflect the change of repository

**Comment by maximskorik** [comment]
I tried to add IO functionality to apLCMS' galaxy wrapper and it worked with test-data in biocontainer. Could we please add a license and create a tagged release so there is a stable url for the recipe to point to? Once that's done I'll put the package to a review at Bioconda.

**Comment by maximskorik** [comment]
Per @xtracko suggestion I moved a recipe for one of apLCMS' dependencies (ROCS) to conda-forge ([PR](https://github.com/conda-forge/staged-recipes/pull/14945/files)). Take a look if you like and let me know if there's something wrong. If everything's fine I'll put it to a review tomorrow morning.

Some context: ROCS is a CRAN package and most CRAN packages don't belong to Bioconda. I initially worked on it in the same branch with aplcms to make it easier to test and debug. Since everything works, there's no need to have them together anymore. This way we can comply with Bioconda guidelines.

**Comment by martenson** [comment]
@maximskorik I've added a license and created a release: https://github.com/RECETOX/recetox-aplcms/releases/tag/6.6.8-recetox0

**Comment by martenson** [comment]
https://anaconda.org/bioconda/r-recetox-aplcms
