### ISSUE TITLE
Remove dependency to r-hdf5r

### ISSUE THREAD

**Issue by hechth** [RECETOX/recetox-aplcms-archive#7]
The [r-hdf5r](https://anaconda.org/conda-forge/r-hdf5r) package has no support for windows, so it is not supported in Bioconda. Removing the dependency and moving the storing functionality to the galaxy wrapper is, therefore, the best solution to avoid this problem.

**Comment by ljocha** [comment]
How much do we depend on reading the apLCMS outputs in H5? IMHO it's just xMSAnnotator which consumes this input, isn't it?

I'd suggest to get rid of H5 synchronously.

**Comment by maximskorik** [comment]
> @hechth I am unsure that supporting windows is a requirement for being accepted as bioconda package. Where would I find this discussion about not accepting it? I do not see it on the [PR](https://github.com/bioconda/bioconda-recipes/pull/28114)

No, there's no such requirement. There was a problem that the package wouldn't install as a runtime dependency because **r-hdf5r** is built for Linux and osx (thus not `noarch`), but if I omitted `noarch` option in the recipe, Bioconda CI would throw `should_be_noarch_generic` error (https://github.com/bioconda/bioconda-recipes/runs/2400553834). I didn't investigate it much further because after I mentioned the problem to @hechth he suggested that it may be better if we don't include this dependency in the package at all.

As of now I know how to fix that so in case we want to include **r-hdf5r** back, that shouldn't be a problem.

**Comment by martenson** [comment]
If this is not about bioconda, I have the following questions then.

What is the reasoning for removing the h5 dependency, what format are we going to replace it with, and what other tools are affected?

**Comment by hechth** [comment]
The reason is that export functionality isn't strictly part of the package, and also wasn't part of the original package.

It is cleaner to keep the export to hdf or parquet etc. inside the galaxy wrapper, rather then putting it into the library.

**Comment by martenson** [comment]
this dependency is actually non-existent in this version of our repo, closing
